name: silent_auth
description: A package that enables seamless user experience for single page web
             applications using OAuth 2.0 - OpenID Connect with the implicit flow.
version: 0.0.7
homepage: https://github.com/jolleekin/silent_auth
author: Man Hoang <jolleekin@outlook.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  test: ^1.3.0
